apiVersion: v1
kind: Pod
metadata:
  name: alpine-x86
spec:
  runtimeClassName: kata-remote-x86-large
  containers:
  - command:
    - /bin/sh
    - -c
    - while true; do echo hello; sleep 10;done
    image: alpine
    #image: docker.cd-caa-c875ab6ccb1204e43cf53a8a7c8281f3-0000.us-south.containers.appdomain.cloud/alpine:latest
    name: test