apiVersion: v1
kind: Pod
metadata:
  name: base-x86
spec:
  runtimeClassName: kata-remote-x86-large
  containers:
  - command: ["sh", "-c", "sleep 99999"]
    securityContext:
        privileged: true
    image: icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.83
    #image: icr.io/continuous-delivery/base-images/base:latest
    name: test