apiVersion: v1
kind: Pod
metadata:
  name: centos-x86
spec:
  runtimeClassName: kata-remote-x86-large
  containers:
  - command: ["sleep", "999999"]
    image: quay.io/centos/centos:stream9
    name: test
    securityContext:
      privileged: true