apiVersion: v1
kind: Pod
metadata:
  name: fedora-x86
spec:
  runtimeClassName: kata-remote-x86-large
  containers:
  - command: ["sleep", "999999"]
    securityContext:
      privileged: true
    image: fedora
    name: test