apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-classname-var-base
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build classname-var!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-classname-var
spec:
  params:
  tasks:
    - name: build-classname-var
      taskRef:
        name: build-classname-var-base
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: listener-classname-var
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: run
      spec:
        securityContext:
          privileged: true
        pipelineRef:
            name: pipeline-classname-var
        taskRunSpecs:
        - pipelineTaskName: build-classname-var
          taskPodTemplate:
            runtimeClassName: $(params.RUNTIMECLASSNAME)
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: listener-classname-var
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: listener-classname-var
spec:
  triggers:
    - binding:
        name: listener-classname-var
      template:
        name: listener-classname-var
